global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'gsdemo'
    metrics_path: '/actuator/prometheus' # Job to scrape application metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:8080']
